[model]
name = "Baseline"
params = { d_model = 128 }

[dataset]
name = "MoveDataset"
file = "data/medium.txt"

[optimizer]
name = "Adam"
params = { lr = 1e-3 }

[scheduler]
name = "CosineAnnealingLR"
params = { T_max = 18430 }

[training]
batch_size = 512
epochs = 10
val_split = 0.1
sequence_length = 128
