[model]
name = "PositionBaseline"
params = { d_model = 128, feature_channels = 32, num_blocks = 10 }

[dataset]
name = "PositionDataset"
file = "data/medium.txt"

[optimizer]
name = "Adam"
params = { lr = 1e-3 }

[scheduler]
name = "CosineAnnealingLR"
params = { T_max = 29483 }

[training]
batch_size = 32
epochs = 1
val_split = 0.1
sequence_length = 128
encode_positions = true
